services:
  app:
    build:
      context: .
    container_name: nextjs_app
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    depends_on:
      - app
      - certbot
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/entrypoint.sh:/entrypoint.sh
      - ./nginx/templates:/etc/nginx/templates
      - certbot_certs:/etc/letsencrypt
      - certbot_challenges:/var/www/certbot
    env_file:
      - .env
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot_ssl
    volumes:
      - certbot_certs:/etc/letsencrypt
      - certbot_challenges:/var/www/certbot
      - ./certbot/init.sh:/init.sh
    env_file:
      - .env
    entrypoint: ["/bin/sh", "/init.sh"]
    restart: always

volumes:
  certbot_certs:
  certbot_challenges:
